platformName: android
platformVersion: 5.1.1
deviceName: xxxx
udid: 127.0.0.1:21503
appPackage: com.iflytek.inputmethod
appActivity: com.iflytek.inputmethod.settingsnew.splash.activity.NewSplashActivity
noReset: True